--- a/.github/workflows/Fuzzers.yaml
+++ b/.github/workflows/Fuzzers.yaml
@@ -25,11 +25,11 @@
         allowed-broken-targets-percentage: 0
         dry-run: false
     - name: Run Fuzzers (${{ matrix.san }})
-      id: build
+      id: run
       uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
       with:
         sanitizer: ${{ matrix.san }}
         oss-fuzz-project-name: 'libzmq'
         allowed-broken-targets-percentage: 0
         dry-run: false
-        fuzz-seconds: 300
+        fuzz-seconds: 300